version: "3.9"

services:

  backend:
    build: ./backend
    container_name: crop_backend
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    container_name: crop_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend